### ISSUE TITLE
insecure login

### ISSUE THREAD

**Issue by ghost** [arenahq/chrome-extension#19]
i'm assuming that this is also the code for the firefox extension since it's a webextension.

when first installing this extension, you have to log in to are.na. this is done over an insecure http connection -- firefox even warns you of this when you focus on the password field.

**Comment by broskoski** [comment]
Thanks, will fix. 

(And this repo is no longer active, we moved the extension code into our main front-end repo).

**Comment by broskoski** [comment]
@brortao upon investigating, you must have an unofficial extension installed. try this https://addons.mozilla.org/en-US/firefox/addon/are-na/

**Comment by ghost** [comment]
hi -- no, it was definitely the official one from the mozilla addon store. i installed it yesterday.

**Comment by ghost** [comment]
that being said, i just reinstalled it and cannot reproduce it again!

**Comment by broskoski** [comment]
Yeah, I can't reproduce either. It might have been an error on the page you were on? I can't see how it could possibly be sending data through non-HTTPS, we don't use non-secure connections to our API anywhere.

The only thing I could imagine would be the iframe window for the extension itself being classified as "insecure" (since its `moz-extension://`). In any case, we don't communicate with our API using non-HTTPS calls (like I said). If you're curious, you can see the repo here: https://github.com/aredotna/ervell/tree/master/src/extension

**Comment by ghost** [comment]
i can't say whether the page i was on caused it but the warning was definitely displayed in the extension's password field. i should've checked the inspector to look at the request, but i didn't think of it at the time!

another thing to note (in case this ever comes up again) is that i was logged in to the are.na website, but had to authenticate with the extension anyway (i don't know if this is the expected behaviour). anyway -- thanks for looking into this :)

**Comment by broskoski** [comment]
No problem, thanks for taking the time to file a ticket!

And yes, this is expected behavior, we don't share cookies or localStorage between the main website and the extension. But you should only have to log-in once and then you should be good.

Thanks again!

**Comment by hxrts** [comment]
should this repo be depreciated if the extension code has moved elsewhere?
